### ISSUE TITLE
Add caseyjr16 as a contributor for Code Review 

### ISSUE THREAD

**Issue by caseyjr16** [moburke/WhatShouldIRead#4]
Hello, I am assigned to code review your team project. Would you mind adding me as a contributor to your project?

**Comment by moburke** [comment]
Hey Casey,

Sure thing.  What's your github username or an email I can enter?
Also, would it be alright if you waited until tomorrow to review?  We're having some issues with merging branches at the moment.

Thanks,
Mollie Burke
________________________________

**Comment by caseyjr16** [comment]
caseyjr16 or add by email: caseyjr07@sbcglobal.net

**Comment by vumd-UC** [comment]
@moburke What is the status on this? Can we close this issue?

**Comment by moburke** [comment]
Added Casey as a contributor
